services:
  - type: web
    name: excellent-institute
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.11.1
      - key: PORT
        value: 10000
    autoDeploy: true 