services:
  - type: web
    name: excellent-institute
    env: node
    buildCommand: |
      npm cache clean --force
      rm -rf node_modules
      rm -f package-lock.json
      npm install --production=false
      npm rebuild express --build-from-source
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.11.1 