name: Deploy to Render

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'
          cache: 'npm'
          
      - name: Install Dependencies
        run: |
          npm cache clean --force
          npm install -g npm@latest
          npm install express@4.17.1 --no-save
          npm install
          
      - name: Deploy to Render
        uses: render-actions/deploy@v1
        with:
          api-key: ${{ secrets.RENDER_API_KEY }}
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          environment: production
          
      - name: Check Deployment Status
        uses: render-actions/status@v1
        with:
          api-key: ${{ secrets.RENDER_API_KEY }}
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          timeout-minutes: 10 